name: Daily Commit

on:
  schedule:
    - cron: '0 9 * * *'   # 매일 09:00 UTC 실행 (한국 시간 18:00쯤)
  workflow_dispatch:       # 수동 실행도 가능

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make a change
        run: |
          echo "Updated at $(date -u)" > daily_commit.txt

      - name: Commit & Push
        run: |
          git config user.name "ysy56"   # ← 본인 GitHub 닉네임
          git config user.email "ysy561356@naver.com"            # ← GitHub 계정에 등록된 이메일
          git add daily_commit.txt
          git commit -m "chore: daily commit" || echo "No changes to commit"
          git push
